spring:
  application:
    name: dubbo-demo-provider

dubbo:
  application:
    name: dubbo-demo-provider
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 30020

server:
  port: 9000